# Generated by Django 3.2 on 2021-06-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('f_name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('phone_no', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('class_opted', models.CharField(choices=[('1', '5'), ('2', '6'), ('3', '7'), ('4', '8'), ('5', '9'), ('6', '10')], default='1', max_length=20)),
                ('marks', models.FloatField()),
                ('date_enrolled', models.DateField(auto_now=True)),
            ],
        ),
    ]
