# Generated by Django 3.2 on 2021-06-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_opted',
            field=models.CharField(choices=[('1', '5'), ('2', '6'), ('3', '7'), ('4', '8'), ('5', '9'), ('6', '10')], default='5', max_length=20),
        ),
    ]
