# Generated by Django 3.2 on 2021-06-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_class_opted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
